# Homepage
commun_homepage:
    path:     /
    defaults: { _controller: CommunBundle:Default:index }

# Page de contact
commun_contact:
    path:     /contact
    defaults: { _controller: CommunBundle:Default:contact}


commun_devise_get_ajax:
    path:     /devise/{id}
    defaults: { _controller: CommunBundle:Default:getCoursAjax }
    options:
       expose: true
