# Homepage de la partie livre
livre_lieu_homepage:
    path:     /
    defaults: { _controller: LivreBundle:Lieu:liste }
# Liste des livre
livre_lieu_liste:
    path:     /
    defaults: { _controller: LivreBundle:Lieu:liste }
# Form d'ajout d'un nouveau lieu
livre_lieu_form_ajax:
    path:     /form/get/
    defaults: { _controller: LivreBundle:Lieu:getFormAjax }
    options:
      expose: true
# Form d'ajout d'un nouveau lieu
livre_lieu_enregistre_ajax:
    path:     /form/enregistre/{typeLieu}
    defaults: { _controller: LivreBundle:Lieu:enregistreAjax }
    options:
      expose: true
# Form d'ajout d'un nouveau lieu
livre_lieu_affiche_arbre_lieu_ajax:
    path:     /form/affiche/arbre
    defaults: { _controller: LivreBundle:Lieu:afficheArbreLieuAjax }
    options:
      expose: true