services:
    # Service de gestion de batch
    commun.batch:
        class: CommunBundle\Service\BatchService
        arguments: ["@doctrine.orm.entity_manager"]
    # Service de mail
    commun.mailer:
        class: CommunBundle\Service\MailerService
        arguments: ["@twig", "@mailer", "%mailer_from%", "@router", "@user.service"]
