services:
    # Extension twig général
    commun.commun_extension:
          arguments: ["@request_stack"]
          class: CommunBundle\Twig\CommunExtension
          tags:
              - { name: twig.extension }
