services:
    # Extension twig général
    commun.commun_extension:
          arguments: ["@request_stack", "%url_dev%"]
          class: CommunBundle\Twig\CommunExtension
          tags:
              - { name: twig.extension }

    # Extension twig news
    commun.news_extension:
          arguments: ["@commun.news"]
          class: CommunBundle\Twig\NewsExtension
          tags:
              - { name: twig.extension }
