# Homepage de la partie livre
book_homepage:
    path:     /
    defaults: { _controller: BookBundle:Livre:liste }
# Liste des livre
book_liste:
    path:     /
    defaults: { _controller: BookBundle:Livre:liste }
# Edition des livres
book_edit:
    path:     /edit
    defaults: { _controller: BookBundle:Livre:edit }

# Détail d'un livre en ajax
book_ajax_edit:
    path:     /ajax/detail/{id}
    defaults: { _controller: BookBundle:Livre:ajaxDetail }
    options:
        expose: true
