book:
    resource: "@BookBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

home:
    path:     /
    defaults: { _controller: CommunBundle:Default:index }

commun:
    resource: "@CommunBundle/Resources/config/routing.yml"
    prefix:   /commun

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"