user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

commun:
    resource: "@CommunBundle/Resources/config/routing.yml"
    prefix:   /commun

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"