services:
    # Service de devise
    devise.devise:
        class: DeviseBundle\Service\DeviseService
        arguments: ["@doctrine.orm.entity_manager", "%url_devise_webservice%", "@transverse.curl"]
    # Service concernant les alertes utilisateurs
    devise.alert:
        class: DeviseBundle\Service\AlertService
        arguments: ["@doctrine.orm.entity_manager", "@commun.mailer"]