# Homepage de la partie livre
livre_homepage:
    path:     /
    defaults: { _controller: LivreBundle:Livre:liste }
# Liste des livre
livre_liste:
    path:     /
    defaults: { _controller: LivreBundle:Livre:liste }
# Edition des livres
livre_edit:
    path:     /edit
    defaults: { _controller: LivreBundle:Livre:edit }

# Détail d'un livre en ajax
livre_ajax_edit:
    path:     /ajax/detail/{id}
    defaults: { _controller: LivreBundle:Livre:ajaxDetail }
    options:
        expose: true
