livre:
    resource: '@LivreBundle/Resources/config/routing/livre.yml'
bibliotheque:
    resource: '@LivreBundle/Resources/config/routing/bibliotheque.yml'
    prefix: 'bibliotheque'
lieu:
    resource: '@LivreBundle/Resources/config/routing/lieu.yml'
    prefix: 'lieu'