# Enregistre des devises
devise_sauve_ajax:
    path:     /sauve/{id}/{seuilMax}/{seuil}
    defaults: { _controller: DeviseBundle:Devise:sauveDeviseAjax }
    requirements:
        id: '\d+'
    options:
       expose: true

# Calcul des sommes en AJAX
devise_calcul_ajax:
    path:     /calcul/{id}/{valeurEuros}/{valeurAutre}
    defaults: { _controller: DeviseBundle:Devise:calculDeviseAjax }
    requirements:
        id: '\d+'
    options:
       expose: true

# Récupère les devises en AJAX
devise_get_ajax:
    path:     /json/{id}
    defaults: { _controller: DeviseBundle:Devise:getCoursAjax }
    requirements:
        id: '\d+'
    options:
       expose: true
# Affiche un bloc HTML en AJAX
devise_affiche_ajax:
    path:     /affiche/{id}
    defaults: { _controller: DeviseBundle:Devise:renderCoursAjax }
    requirements:
        id: '\d+'
    options:
       expose: true