#Charge les news en Ajax
commun_news_charge_ajax:
    path:     /news/{id}
    defaults: { _controller: CommunBundle:News:chargeNews, id: '' }
    requirements:
        id: '\d+'
    options:
       expose: true
#Liste des news
commun_news_liste:
    path:     /news/liste
    defaults: { _controller: CommunBundle:News:liste}
# Enregistre une news
commun_news_enregistre:
    path:     /news/enregistre/{id}
    defaults: { _controller: CommunBundle:News:enregistreNews, id: null}
    requirements:
        id: '\d+'
# Supprime une news
commun_news_supprimer:
    path:     /news/delete/{id}
    defaults: { _controller: CommunBundle:News:deleteNews, id: null}
    requirements:
        id: '\d+'

# Détail d'une news
commun_news_detail_ajax:
    path:     /news/ajax/detail/{id}
    defaults: { _controller: CommunBundle:News:ajaxDetail, id: null}
    requirements:
        id: '\d+'
    options:
       expose: true

# Recherche des news
commun_news_recherche_ajax:
    path:     /news/ajax/recherche/
    defaults: { _controller: CommunBundle:News:ajaxRecherche}
    requirements:
        id: '\d+'
    options:
       expose: true