services:
    # form des pièces
  livre.form.piece:
    class: LivreBundle\Form\PieceType
    arguments: ["@security.token_storage"]
    tags:
      - { name: form.type }
    # form des meubles
  livre.form.meuble:
    class: LivreBundle\Form\MeubleType
    arguments: ["@security.token_storage"]
    tags:
      - { name: form.type }
    # form des meubles
  livre.form.etagere:
    class: LivreBundle\Form\EtagereType
    arguments: ["@security.token_storage"]
    tags:
      - { name: form.type }
      # form des isbn
  livre.form.recherche_isbn:
    class: LivreBundle\Form\RechercheISBNLivreType
    arguments: ["@security.token_storage"]
    tags:
      - { name: form.type }