services:
    # Service gérant l'appel google books
    livre.google_get_livre_service:
        class: LivreBundle\Service\GoogleGetLivreService
        arguments: ["@doctrine.orm.entity_manager", "%google_books_api%", "@transverse.curl","@livre.image" ]

  # Service gérant les images d'un livre
    livre.image:
        class: LivreBundle\Service\LivreImageService
        arguments: ["%path_relatif_upload_image%","%path_absolu_upload_image_livre%",  "@transverse.curl" ]