services:
    # Extension sur les livres
    livre.extension:
          arguments: ["@livre.image"]
          class: LivreBundle\Twig\LivreExtension
          tags:
              - { name: twig.extension }
